import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import NavBar from "@/components/NavBar";
import React from "react";

export default function App({ Component, pageProps }: AppProps) {
  return (
          <>
            <Head>
              <title>Sodrul&#39;s Next JS</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
              <NavBar />
              <main>
                <Component {...pageProps} />
              </main>
            </div>
          </>
      )

  ;


}
