# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Build and Publish Docker Image
        run: |
          mvn clean package jib:dockerBuild -DskipTests -Djib.to.image=${{ secrets.DOCKER_USERNAME }}/bookmarker-api:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api

  build-bookmarker-ui:
    name: Build bookmarker-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-ui-nextjs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: bookmarker-ui-nextjs/yarn.lock
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Build and Publish Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-ui-nextjs